import { Farm, InspectorPreferences } from "./types";

// Sample farms based on real Intact Platform export structure (PA region)
export const SAMPLE_FARMS: Farm[] = [
  {
    id: "farm-1",
    name: "Patrick H. Ciarrocchi",
    street: "3876 Route 35 South",
    street2: "",
    city: "East Waterford",
    state: "PA",
    zip: "17021",
    municipality: "Juniata",
    country: "UNITED STATES",
    address: "3876 Route 35 South, East Waterford, PA 17021",
    lat: 40.3984,
    lng: -77.6854,
    email: "phc.ridgeview@gmail.com",
    phone: "717-363-2941",
    mobile: "",
    priority: "urgent",
    auditType: "Annual Inspection (New Applicant)",
    nopId: "8210009373",
    auditNumber: "AO-016755",
    services: ["NOP Crop", "NOP Handling"],
    assignedSites: "",
    completionFrom: "2026-03-15",
    completionUntil: "2026-04-20",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 4.5,
    notes: "",
  },
  {
    id: "farm-2",
    name: "Hanover Foods Corporation",
    street: "1175 Wilson Ave",
    street2: "",
    city: "Hanover",
    state: "PA",
    zip: "17331",
    municipality: "York",
    country: "UNITED STATES",
    address: "1175 Wilson Ave, Hanover, PA 17331",
    lat: 39.8007,
    lng: -76.9831,
    email: "swallen@hanoverfoods.com",
    phone: "(717)900-1598",
    mobile: "",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210001741",
    auditNumber: "AO-016728",
    services: ["NOP Handling"],
    assignedSites: "",
    completionFrom: "2026-04-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "",
  },
  {
    id: "farm-3",
    name: "Backenstoes Farms LLC",
    street: "9860 Mountain Rd",
    street2: "",
    city: "Grantville",
    state: "PA",
    zip: "17028",
    municipality: "DAUPHIN",
    country: "UNITED STATES",
    address: "9860 Mountain Rd, Grantville, PA 17028",
    lat: 40.3890,
    lng: -76.7283,
    email: "tjback@comcast.net",
    phone: "717-269-5454",
    mobile: "",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210006778",
    auditNumber: "AO-017619",
    services: ["NOP Crop"],
    assignedSites: "",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "",
  },
  {
    id: "farm-4",
    name: "The Pennsylvania State University",
    street: "2710 W Pine Grove Rd",
    street2: "",
    city: "Pennsylvania Furnace",
    state: "PA",
    zip: "16865",
    municipality: "CENTRE",
    country: "UNITED STATES",
    address: "2710 W Pine Grove Rd, Pennsylvania Furnace, PA 16865",
    lat: 40.7264,
    lng: -77.9153,
    email: "avh111@psu.edu",
    phone: "603-562-0754",
    mobile: "",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210003449",
    auditNumber: "AO-017622",
    services: ["NOP Crop"],
    assignedSites: "The Pennsylvania State University ROSE Site",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "Sites: The Pennsylvania State University ROSE Site",
  },
  {
    id: "farm-5",
    name: "Stephen L. Musser",
    street: "810 S. 14th Avenue",
    street2: "",
    city: "Lebanon",
    state: "PA",
    zip: "17042",
    municipality: "LEBANON",
    country: "UNITED STATES",
    address: "810 S. 14th Avenue, Lebanon, PA 17042",
    lat: 40.3357,
    lng: -76.4113,
    email: "srmusser99@comcast.net",
    phone: "(717) 228-0477",
    mobile: "(717) 222-1628",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210003289",
    auditNumber: "AO-017626",
    services: ["NOP Crop"],
    assignedSites: "",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "",
  },
  {
    id: "farm-6",
    name: "Spiral Path Farm",
    street: "538 Spiral Path Lane",
    street2: "",
    city: "Loysville",
    state: "PA",
    zip: "17047",
    municipality: "Perry",
    country: "UNITED STATES",
    address: "538 Spiral Path Lane, Loysville, PA 17047",
    lat: 40.3481,
    lng: -77.3694,
    email: "will@spiralpathfarm.com",
    phone: "(717) 789-4433",
    mobile: "(717) 636-2485",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210003729",
    auditNumber: "AO-017632",
    services: ["NOP Crop", "NOP Handling"],
    assignedSites: "",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 4.5,
    notes: "",
  },
  {
    id: "farm-7",
    name: "Seedway, LLC",
    street: "99 Industrial Road",
    street2: "",
    city: "Elizabethtown",
    state: "PA",
    zip: "17022",
    municipality: "LANCASTER",
    country: "UNITED STATES",
    address: "99 Industrial Road, Elizabethtown, PA 17022",
    lat: 40.1526,
    lng: -76.6019,
    email: "pguigley@seedway.com",
    phone: "570-939-1849",
    mobile: "",
    priority: "do_not_inspect",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210003668",
    auditNumber: "AO-017618",
    services: ["NOP Handling", "US/Canada Equivalence"],
    assignedSites: "",
    completionFrom: "2026-05-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 4.5,
    notes: "",
  },
  {
    id: "farm-8",
    name: "Scott and Eda Case",
    street: "476 Jackson Hill Rd.",
    street2: "",
    city: "Aaronsburg",
    state: "PA",
    zip: "16820",
    municipality: "CENTRE",
    country: "UNITED STATES",
    address: "476 Jackson Hill Rd., Aaronsburg, PA 16820",
    lat: 40.8931,
    lng: -77.4506,
    email: "casefarm@hotmail.com",
    phone: "(814) 349-8275",
    mobile: "814-777-7838",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210003423",
    auditNumber: "AO-017628",
    services: ["NOP Crop"],
    assignedSites: "",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "",
  },
  {
    id: "farm-9",
    name: "Benjamin C. Mearns",
    street: "680 King Road",
    street2: "",
    city: "Gettysburg",
    state: "PA",
    zip: "17325",
    municipality: "ADAMS",
    country: "UNITED STATES",
    address: "680 King Road, Gettysburg, PA 17325",
    lat: 39.8309,
    lng: -77.2311,
    email: "farmer@mudcollege.com",
    phone: "717-677-2530",
    mobile: "",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210006481",
    auditNumber: "AO-017629",
    services: ["NOP Crop"],
    assignedSites: "",
    completionFrom: "2026-05-01",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "",
  },
  {
    id: "farm-10",
    name: "Crawford Organics LLC",
    street: "727 Rettew Mill Rd.",
    street2: "",
    city: "Lititz",
    state: "PA",
    zip: "17543",
    municipality: "LANCASTER",
    country: "UNITED STATES",
    address: "727 Rettew Mill Rd., Lititz, PA 17543",
    lat: 40.1574,
    lng: -76.3069,
    email: "jk@crawfordorganics.com",
    phone: "(717) 824-9172",
    mobile: "",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210001382",
    auditNumber: "AO-016697",
    services: ["NOP Crop", "NOP Handling"],
    assignedSites: "Crawford Organics LLC: Packing Shed",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 4.5,
    notes: "Sites: Crawford Organics LLC: Packing Shed",
  },
  {
    id: "farm-11",
    name: "Dennis L. Wenger",
    street: "10581 Allentown Blvd",
    street2: "",
    city: "Annville",
    state: "PA",
    zip: "17003",
    municipality: "LEBANON",
    country: "UNITED STATES",
    address: "10581 Allentown Blvd, Annville, PA 17003",
    lat: 40.3284,
    lng: -76.5139,
    email: "beulahlandjerseys@gmail.com",
    phone: "717-471-3107",
    mobile: "",
    priority: "normal",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210001114",
    auditNumber: "AO-017649",
    services: ["NOP Crop"],
    assignedSites: "",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "",
  },
  {
    id: "farm-12",
    name: "Costas Foods, Inc.",
    street: "130 West Bacon Street",
    street2: "",
    city: "Pottsville",
    state: "PA",
    zip: "17901",
    municipality: "Schuylkill",
    country: "UNITED STATES",
    address: "130 West Bacon Street, Pottsville, PA 17901",
    lat: 40.6856,
    lng: -76.1955,
    email: "ryan@costasfoodsinc.com",
    phone: "570-622-2001",
    mobile: "",
    priority: "do_not_inspect",
    auditType: "Annual Inspection (Renewal)",
    nopId: "8210001368",
    auditNumber: "AO-017620",
    services: ["NOP Handling"],
    assignedSites: "",
    completionFrom: "2026-03-15",
    completionUntil: "2026-11-15",
    unannounced: false,
    samplingRequired: false,
    year: 2026,
    estimatedDurationHours: 3,
    notes: "",
  },
];

export const SAMPLE_PREFERENCES: InspectorPreferences = {
  inspectorName: "Levi Sterner",
  inspectorEmail: "levisterner15@gmail.com",
  inspectorPhone: "",
  certifications: ["NOP Crop", "NOP Handling"],
  homeLat: 40.2732,
  homeLng: -76.8867,
  homeAddress: "Harrisburg, PA",
  maxDailyDriveMiles: 200,
  maxDayTripMiles: 75,
  preferredTripLengthDays: 4,
  tripStyle: "linear",
  restDaysBetweenTrips: 2,
  workStartHour: 8,
  workEndHour: 17,
  availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
  maxDailyInspections: 3,
  annualInspectionTarget: 100,
  startDate: new Date().toISOString().split("T")[0],
  // v2: Day trip vs. travel trip preferences
  dayTripPrefs: {
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    maxDailyInspections: 3,
    maxOneWayMiles: 75,
  },
  travelTripPrefs: {
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    maxDailyInspections: 4,
    preferredTripLengthDays: 4,
    restDaysBetweenTrips: 2,
    tripStyle: "linear",
  },
  lunchPreference: {
    takeLunchBreak: true,
    lunchBreakMinutes: 30,
  },
  dayTripThresholdMinutes: 180, // 3 hours one-way
};
